### ISSUE TITLE
Include libraries in the linting

### ISSUE THREAD

**Issue by adrianbrink** [SublimeLinter/SublimeLinter-javac#11]
Hi,

whenever I import another library it is linted as an error, because it cannot resolve the symbol.

How do I either tell the linter to stop linting these things or how can I get the linter to properly lint these things.

Thank you very much :-)

**Comment by 25A0** [comment]
Hi,

I had the same problem, and was eventually able to solve this by passing the `-classpath` and `-sourcepath` arguments to `javac`. I tried to explain how to do this [in this updated Readme][1].
Does this help you?

I made a pull request for this; feel free to suggest improvements in #12 if you miss something.

[1]: https://github.com/25A0/SublimeLinter-javac/tree/javac-option-docs#passing-options-to-javac

**Comment by adrianbrink** [comment]
Okay, so I think I can fix it like this, however I would like to know something else.

What's the difference between the sourcepath and the classpath and should I just add these settings to the file that opens under "Preferences -> Package Settings -> SublimeLinter -> Settings - User"?

I'm currently adding this to the user preferences file:

```
{
    "javac": {
        "lint": "all,-deprecation",
        "args": [
            "-encoding", "UTF8",
            "-cp", "${project}/lib/some_lib.jar:${project}/lib/some_other_lib.jar",
            "-sourcepath", "${project}/src/"
            ]
    }
}
```
This is my entire file.

Thank you for the help.

**Comment by 25A0** [comment]
Since settings like the class path are usually different for each project, I store these settings in my `sublime-project` files, like so:

```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"SublimeLinter":
	{
		"linters":
		{
			"javac": {
				"lint": "all",
				"args": [
					"-d", "${project}/bin/",
					"-encoding", "UTF8",
					 "-cp", "${project}/lib/some_lib.jar:${project}/lib/some_other_lib.jar",
					"-sourcepath", "${project}/src/"
				]
			}
		}
	}
}
```

If you want to store it in "Preferences -> Package Settings -> SublimeLinter -> Settings - User", I believe that the file needs to be structured like this:

```
{
    "user": {
        "linters": {
            "javac": {
                "@disable": false,
                "args": [
                    "-encoding", "UTF8",
                    "-cp", "${project}/lib/some_lib.jar:${project}/lib/some_other_lib.jar",
                    "-sourcepath", "${project}/src/"
                ]
            }
        }
    }
}
```

>  What's the difference between the sourcepath and the classpath

[This SO answer][1] tries to explain the difference. I usually just use `-classpath`. It seems to work fine, and form a few tests it doesn't seem like there is a performance difference, either.

[1]: http://stackoverflow.com/questions/2441760/differences-between-classpath-and-sourcepath-options-of-javac

**Comment by adrianbrink** [comment]
Mh,

so I've added this to my user settings.

```
        "linters": {
            "javac": {
                "@disable": false,
                "args": [],
                "excludes": [
                    "-encoding",
                    "UTF8",
                    "-cp",
                    ".:/Users/aevitas/Desktop/Projects/02_Algorithms_and_Data_Structures/libs/algs4.jar"
                ],
                "lint": "all"
            },
```

And this to my project settings file. Is it correctly named just "sublime-project"?

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter":
    {
        "linters":
        {
            "javac": {
                "lint": "all",
                "args": [
                    "-encoding", "UTF8",
                     "-cp", ".:/Users/aevitas/Desktop/Projects/02_Algorithms_and_Data_Structures/libs/algs4.jar"
                ]
            }
        }
    }
}
```

However, when importing the library package like this: "import edu.princeton.cs.algs4.*;", both the import statement and the classes from within the package get highlighted as errors.

Am I doing something wrong here?

**Comment by 25A0** [comment]
For the user settings: You added the arguments to the `excludes` entry instead of the `args` entry ;)

For the project settings: Hmm I guess I could have explained this better..
When you get tired of adding a certain folder to your SublimeText workspace whenever you start working on a project, you can create a Sublime-Text Project that will automatically restore that workspace.
 
First, add the root folder of your project to your workspace via "Project" -> "Add folder to project...", and then click "Project" -> "Save project as..." from Sublime's application menu. Saving the project creates a file `yourProjectName.sublime-project`. I usually just save this file in the root directory of the project itself. When you open that file you will probably see
```
{
    "folders":
    [
        {
            "path": "./relative/path/to/your/project-s/root/folder"
        }
    ]
}
```
To this file you can now add the SublimeLinter settings as described above, and they should be applied automatically whenever you open this project in SublimeText.

[Here][1] you can find more info on how to use projects.

[1]: http://www.sublimetext.com/docs/3/projects.html

**Comment by adrianbrink** [comment]
Awesome, I finally fixed it. Thank you very much for all your help :-)
